In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("AUD_CAD.csv",index_col="Date")

In [56]:
df1= pd.DataFrame({'Date':rollingCorr.index, 'values':rollingCorr.values})

In [27]:
df1.to_csv("Haha.csv",na_rep="NaN")

In [57]:
df["Rolling correlation DF2 % Rank"]=df1["values"]

In [44]:
df2=pd.read_excel("EUR_AUD_with Histogram.xlsx")

In [46]:
df2val=df2["Price"].pct_change(periods=20)

In [51]:
print(df2val)

0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
          ...    
457      0.006779
458    432.977725
459    435.425341
460    434.455188
461    431.882087
Name: Price, Length: 462, dtype: float64


In [80]:
val=change_in_price(df2["Price"].values,20)

In [81]:
val

[nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 -0.01209996392793182,
 -0.004666343837847685,
 -0.014617563739376782,
 -0.008697687363999753,
 -0.009223878330844835,
 -0.012290970961311404,
 -0.00433443955128767,
 -0.010152734647316003,
 -0.01254898479410532,
 -0.012979369700037987,
 -0.012138105796642424,
 -0.011044062393259725,
 -0.009583048876077816,
 -0.016453219494841714,
 -0.013499658236500388,
 -0.015064944958671408,
 -0.010969756989411113,
 -0.013487598267694488,
 -0.010633297338499636,
 -0.0025568794650221286,
 -0.0112630373950648,
 -0.009404587913833591,
 -0.005476158675036734,
 -0.0016221833574126922,
 0.0032273578696907458,
 0.0051968919071588085,
 0.0071729692317371516,
 0.004142512534889238,
 0.0017750993360749327,
 0.00290569136504323,
 0.006341803737201644,
 0.009932220574153727,
 0.014499286304560181,
 0.008894631857585579,
 0.012413948764247852,
 0.01596701649175414,
 0.013246278008922713,
 0.016056350

In [82]:
len(val)

462

In [83]:
df2["Price"].values

array([  1.59929,   1.59753,   1.61172,   1.59463,   1.59526,   1.5945 ,
         1.59185,   1.59392,   1.59681,   1.60071,   1.59766,   1.5984 ,
         1.59712,   1.60006,   1.60137,   1.59891,   1.59252,   1.59602,
         1.59104,   1.58017,   1.59011,   1.5885 ,   1.58088,   1.58068,
         1.57514,   1.58498,   1.5779 ,   1.57702,   1.5802 ,   1.5785 ,
         1.58094,   1.58196,   1.57416,   1.58004,   1.57518,   1.57524,
         1.57478,   1.5743 ,   1.57614,   1.5724 ,   1.5737 ,   1.57227,
         1.57812,   1.58024,   1.59326,   1.5893 ,   1.58358,   1.58301,
         1.5831 ,   1.59103,   1.59783,   1.59732,   1.59422,   1.59498,
         1.6008 ,   1.59592,   1.59999,   1.60952,   1.60652,   1.60469,
         1.61646,   1.61356,   1.61764,   1.6189 ,   1.62438,   1.6246 ,
         1.61578,   1.62286,   1.62186,   1.61992,   1.61966,   1.61738,
         1.61842,   1.6128 ,   1.61134,   1.61197,   1.60904,   1.6101 ,
         1.61124,   1.60828,   1.61212,   1.61722, 

In [60]:
rollingCorr.values

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan, -0.59163612,
       -0.58636811, -0.63364671, -0.60358053, -0.46720991, -0.53731694,
       -0.72785328, -0.73378139, -0.66985739, -0.72161043, -0.75276424,
       -0.79587106, -0.83091443, -0.83980493, -0.84508373, -0.85695344,
       -0.86594799, -0.85624687, -0.85929674, -0.88245016, -0.89292622,
       -0.89930042, -0.92745876, -0.9468354 , -0.94802072, -0.94680384,
       -0.94527028, -0.94222388, -0.9515242 , -0.9385155 , -0.93191765,
       -0.91078621, -0.88210756, -0.84123061, -0.77732582, -0.68345925,
       -0.44253411, -0.35500725, -0.21487049, -0.2422748 , -0.2294127 ,
       -0.03750569,  0.1004203 ,  0.16197165,  0.17875851,  0.15553889,
        0.11642811,  0.09430251,  0.01747856, -0.09623255, -0.14

In [62]:
dfval=df["Price"].pct_change(periods=20)

In [64]:
dfval.values

array([            nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
        2.33516484e-03,  2.49044976e-03,  6.87601975e-03,  1.13794680e-02,
        4.11788368e-03,  4.96343567e-03,  6.51311067e-03,  9.89176251e-03,
        1.28935278e-02,  5.68199754e-03,  9.88932374e-03,  7.03507019e-03,
        2.35804565e-03,  5.12782946e-04,  6.80794646e-03,  8.64574558e-03,
        3.60333783e-03,  5.19359878e-03, -3.85401091e-03,  3.28835709e-03,
       -5.79795701e-04, -2.45268321e-03, -1.92560636e-03, -5.99375388e-03,
       -4.48052290e-03, -6.90817186e-03, -1.18721749e-02, -1.15671798e-02,
       -1.70143389e-02, -1.26913379e-02, -1.80119177e-02, -1.72402991e-02,
       -1.75548655e-02, -

In [46]:
d=pd.DataFrame({"name":"a","imp":["df1","ax"],"flag":True})

In [47]:
d

name  imp  flag
0    a  df1  True
1    a   ax  True

In [48]:
d1=pd.DataFrame({"name":"b","imp":["df2","ax"],"flag":False})

In [49]:
d1

name  imp   flag
0    b  df2  False
1    b   ax  False

In [50]:
df3=pd.concat([d,d1])

In [51]:
df3

name  imp   flag
0    a  df1   True
1    a   ax   True
0    b  df2  False
1    b   ax  False

In [19]:
dff=df3.loc[df3['imp'].isin(['one','three'])]

In [22]:
dff.empty

True

In [2]:
dfDiverge=pd.read_csv("ImpVar.csv",index_col=False)

In [3]:
dfDiverge=dfDiverge.loc[dfDiverge['imp_var'].isin(['Divergence Factor 1','Divergence Factor 2','Divergence Factor 3','Divergence Factor 4'])]

In [4]:
dfDiverge

Unnamed: 0 instrumen_name              imp_var     score  flag
2           8        AUD_CAD  Divergence Factor 2  0.106304  True

In [5]:
dfDiverge.reset_index(drop=True,inplace=True)


In [6]:
dfDiverge

Unnamed: 0 instrumen_name              imp_var     score  flag
0           8        AUD_CAD  Divergence Factor 2  0.106304  True

In [20]:
def MinMax_Diff(lst,period):
    anslst=[]
    j=0
    for i in range(0,len(lst)):
        if i>(period-2):
            sublst=lst[j:i+1]
            max1=np.nanmax(sublst)
            min1=np.nanmin(sublst)
            ans=max1-min1
            anslst.append(ans)
            j=j+1
        else:    
            anslst.append(np.nan)
    return anslst

def percent_change(col,period):
    l=[]
    j=0
    for i in range(0,len(col)):
        if i>(period-2):
            a=col[i]-col[j]
            b=a/col[j]
            l.append(b)
            j=j+1
        else:
            l.append(np.nan)
    return l

In [21]:
def calculation(df):
    for index, row in df.iterrows():
        inst_name=row["instrumen_name"]
        imp_var=row["imp_var"]
        flag=row["flag"]
        readDf=pd.read_csv(inst_name+".csv")
        rollingCorrdf=readDf[imp_var].rolling(20).corr(readDf['Price']) #cal. rolling imp var
        rollingCorrAvg=readDf['% Rank of DF Avgs'].rolling(20).corr(readDf['Price']) #fixed
        nperiod_price_change=percent_change(readDf['Price'].values,20) #fixed
        nperiod_df_change=percent_change(readDf[imp_var].values,20) #cal. div.Factor %age change
        nperiod_MinMax_df=MinMax_Diff(nperiod_df_change,20) #cal MinMax Diverg. difference
        nperiod_MinMax_price=MinMax_Diff(readDf["Price"].values,20) #fixed ,cal MinMax Price difference
        df_duration=np.array(nperiod_MinMax_df)/np.array(nperiod_MinMax_price)
        print(df_duration)
        
        readDf["Rolling correlation "+imp_var+" % Rank"]=rollingCorrdf
        readDf["Rolling correlation Avg DF % Rank"]=rollingCorrAvg
        readDf["20 period percentage price change"]=nperiod_price_change
        readDf["20 period percentage " +imp_var+" change"]=nperiod_df_change
        readDf["20 PERIOD MIN MAX DIVERGENCE DIFF"]=nperiod_MinMax_df
        readDf["20 PERIOD MIN MAX PRICE DIFF"]=nperiod_MinMax_price
        readDf["DIVERGENCE DURATION"]=df_duration
       
        if flag==True:
            readDf.to_csv("man_select_inst"+"\\"+inst_name+"_impvar"+".csv",na_rep="NaN")
        else:
            readDf.to_csv("rule_select_inst"+"\\"+inst_name+"_impvar"+".csv",na_rep="NaN")

In [22]:
calculation(dfDiverge)

[          nan           nan           nan           nan           nan
           nan           nan           nan           nan           nan
           nan           nan           nan           nan           nan
           nan           nan           nan           nan    0.
   41.42667972   54.67095308   54.67095308   54.67095308   54.67095308
   49.75366481   49.75366481   40.84428762   40.84428762   40.84428762
   40.84428762   40.84428762   40.84428762   40.84428762   40.84428762
   40.84428762   49.82423738   49.82423738   49.82423738   36.43298694
   35.11313164   34.43944805   35.16803405   33.44430506   36.48419669
   33.45012868   33.45012868   37.54170964   37.54170964   35.64086358
   34.57525314   28.31969811   29.27477043   23.27873311   23.87619109
   12.69896485   11.15518714   12.37005251   11.77265447   17.21292146
   26.55204759   28.80942927   29.02965336   29.02965336   32.23488364
   32.23488364   33.88921456   42.94423407   46.77808121   48.40211875
   64.66558868

In [23]:
if np.nan in [np.nan,np.nan,1,2,3]:
    print("yes")

yes


In [52]:
2>np.nan

False

In [64]:
np.nanmax([np.nan,np.nan,1,2,3,np.nan,33])

33.0